#pragma once

namespace frames
{
	enum class FRAME_TYPES
	{
		//SHADER_CURL_NOISE,
		SHADER_KALEIDOSCOPE_TUNNEL,
		//GEOMETRY_CUBES_RING,

		SHADER_TEMPLATE,

		SHADER_CIRCLE_MANDALA,

		SHADER_SIMPLE_NOISE,
		SHADER_SIMPLE_NOISE_MODE1,
		SHADER_SIMPLE_NOISE_MODE2,
		SHADER_SIMPLE_NOISE_MODE3,
		
		SHADER_PLASTIC_NOISE,
		SHADER_PLASTIC_NOISE_MODE1,
		SHADER_PLASTIC_NOISE_MODE2,
		SHADER_PLASTIC_NOISE_MODE3,

		SHADER_FUR_NOISE,
		SHADER_FUR_NOISE_MODE1,
		SHADER_FUR_NOISE_MODE2,
		SHADER_FUR_NOISE_MODE3,

		SHADER_METABALLS,

		SHADER_SPLINE_TUNNEL,	
		SHADER_SPLINE_TUNNEL_MODE1,
		SHADER_SPLINE_TUNNEL_MODE2,
		SHADER_SPLINE_TUNNEL_MODE3,

		GEOMETRY_SQUARES,
		GEOMETRY_TRIANGLES,
		GEOMETRY_HEXAGON,
		GEOMETRY_INFINITY_DOTS,

		GEOMETRY_MONDRIAN_ANIMATED,
		GEOMETRY_MONDRIAN_ANIMATED_MODE1,
		GEOMETRY_MONDRIAN_ANIMATED_MODE2,
		GEOMETRY_MONDRIAN_ANIMATED_MODE3,

		GEOMETRY_MONDRIAN_CUBE,
		GEOMETRY_MONDRIAN_PING_PONG,
		GEOMETRY_MONDRIAN_PING_PONG_MODE1,
		GEOMETRY_MONDRIAN_PING_PONG_MODE2,
		GEOMETRY_MONDRIAN_PING_PONG_MODE3,
		GEOMETRY_MONDRIAN_PING_PONG_HOR,


		GEOMETRY_TWO_CIRCLES,

		CUBES_ARRAY_3D,
		//CUBES_STEPS_3D,
		CUBES_STEPS_3D_MODE1,
		CUBES_STEPS_3D_MODE2,
		CUBES_STEPS_3D_MODE3,


		CUBES_STEPS_LINES_3D,
		CUBES_WAVE_3D,
	
		AUTOMA_GAME_OF_LIFE,
		AUTOMA_SNAKES_LIFE,

		NAUTILUS,
		NAUTILUS_MODE1,
		NAUTILUS_MODE2,
		NAUTILUS_MODE3,

		SHADER_PIXEL_METABALLS,

		ALICE_TUNNEL,
		ALICE_GRID,
		ALICE_ROOM,
		ALICE_NOISE,

		GLITCH_SIMPLE,

		RANDOM_SQUARES,
		RANDOM_CIRCLES,
		DISTORT_GRID,
		HYPNO_TUNNEL,
		ROTATED_GRID,

		DOTS_ROTATION,

		SHADER_APOLLO_FRACTAL,
		SHADER_APOLLO_FRACTAL_MODE1,
		SHADER_APOLLO_FRACTAL_MODE2,
		SHADER_APOLLO_FRACTAL_MODE3,
		SHADER_APOLLO_FRACTAL_MODE4,

		GEOMETRY_APOLLO_FRACTAL_INF_ZOOM,

		FAMILY_TRAIN,

		SIZE
	};

	enum class VIEW_TYPES
	{
		NONE,
		ONE_ARTWORK,
		THREE_ARTWORKS,
		ONE_LARGE_ARTWORK,
		MIXED
	};
}